prompt_task:
  description: 'Given a natural language description of an image or scene, your task
    is to convert it into a highly-optimized, one-line prompt for a Stable Diffusion
    model. First, use the PathFinderTool to locate the correct local image path from
    the given image name. Then, apply the DescribeImageTool on the local image path
    to generate a detailed visual description. Optionally, check the PGImageTool to
    find any previously saved descriptions for the image path. After retrieving the
    image description, generate a highly detailed, visually rich one-line prompt.
    Next, use the PromptValidationTool to validate the prompt and rewrite any sensitive
    content to avoid generation filters. The final prompt must: - Include a **clearly
    defined subject** - Capture the **environmental context** (e.g., foggy forest,
    neon-lit alley, candlelit library) - Reference **lighting or camera techniques**
    (e.g., volumetric light, soft focus, ultra-wide angle) - Mention the **artistic
    style or medium** (e.g., digital painting, concept art, watercolor, cyberpunk)
    - Optionally include **famous artist references** for better stylistic alignment
    (e.g., by Artgerm, Ghibli, Loish, Moebius) Avoid: - Repeating adjectives - Generic
    phrases like “beautiful” or “cool” - Camera brand names or model-specific jargon
    - Abstract or subjective terms not visually actionable Ensure the final output
    is syntactically tight, visual-heavy, and directly compatible with Stable Diffusion,
    SDXL, or Midjourney. image_name: {image_name}'
  expected_output: "You response should be in the format below:\n<result>\n  <positive_prompt>\n\
    \    ....\n  </positive_prompt>\n  <negative_prompt>\n  ....\n  </negative_prompt>\n\
    <result>\n"
  agent: prompt_engineer
